// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/prompt/prompt.proto

package prompt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HostRequest encodes either an initial request to perform prompt hosting or a
// follow-up response to a message or prompt.
type HostRequest struct {
	// AllowPrompts indicates whether or not the hoster will allow prompts. If
	// not, it will only receive message requests. This field may only be set on
	// the initial request.
	AllowPrompts bool `protobuf:"varint,1,opt,name=allowPrompts,proto3" json:"allowPrompts,omitempty"`
	// Response is the prompt response, if any. On the initial request, this
	// must be an empty string. When responding to a prompt, it may be any
	// value. When responding to a message, it must be an empty string.
	Response             string   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostRequest) Reset()         { *m = HostRequest{} }
func (m *HostRequest) String() string { return proto.CompactTextString(m) }
func (*HostRequest) ProtoMessage()    {}
func (*HostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b032e72dba0447, []int{0}
}

func (m *HostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostRequest.Unmarshal(m, b)
}
func (m *HostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostRequest.Marshal(b, m, deterministic)
}
func (m *HostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostRequest.Merge(m, src)
}
func (m *HostRequest) XXX_Size() int {
	return xxx_messageInfo_HostRequest.Size(m)
}
func (m *HostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostRequest proto.InternalMessageInfo

func (m *HostRequest) GetAllowPrompts() bool {
	if m != nil {
		return m.AllowPrompts
	}
	return false
}

func (m *HostRequest) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// HostResponse encodes either an initial response to perform prompt hosting or
// a follow-up request for messaging or prompting.
type HostResponse struct {
	// Identifier is the prompter identifier. It is only set in the initial
	// response sent after the initial request.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// IsPrompt indicates if the response is requesting a prompt (as opposed to
	// simple message display).
	IsPrompt bool `protobuf:"varint,2,opt,name=isPrompt,proto3" json:"isPrompt,omitempty"`
	// Message is the message associated with the prompt or message.
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostResponse) Reset()         { *m = HostResponse{} }
func (m *HostResponse) String() string { return proto.CompactTextString(m) }
func (*HostResponse) ProtoMessage()    {}
func (*HostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b032e72dba0447, []int{1}
}

func (m *HostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostResponse.Unmarshal(m, b)
}
func (m *HostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostResponse.Marshal(b, m, deterministic)
}
func (m *HostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostResponse.Merge(m, src)
}
func (m *HostResponse) XXX_Size() int {
	return xxx_messageInfo_HostResponse.Size(m)
}
func (m *HostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostResponse proto.InternalMessageInfo

func (m *HostResponse) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *HostResponse) GetIsPrompt() bool {
	if m != nil {
		return m.IsPrompt
	}
	return false
}

func (m *HostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PromptRequest encodes a request for prompting by a specific prompter.
type PromptRequest struct {
	// Prompter is the prompter identifier.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Prompt is the prompt to present.
	Prompt               string   `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromptRequest) Reset()         { *m = PromptRequest{} }
func (m *PromptRequest) String() string { return proto.CompactTextString(m) }
func (*PromptRequest) ProtoMessage()    {}
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b032e72dba0447, []int{2}
}

func (m *PromptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptRequest.Unmarshal(m, b)
}
func (m *PromptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptRequest.Marshal(b, m, deterministic)
}
func (m *PromptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptRequest.Merge(m, src)
}
func (m *PromptRequest) XXX_Size() int {
	return xxx_messageInfo_PromptRequest.Size(m)
}
func (m *PromptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromptRequest proto.InternalMessageInfo

func (m *PromptRequest) GetPrompter() string {
	if m != nil {
		return m.Prompter
	}
	return ""
}

func (m *PromptRequest) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

// PromptResponse encodes the response from a prompter.
type PromptResponse struct {
	// Response is the response returned by the prompter.
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromptResponse) Reset()         { *m = PromptResponse{} }
func (m *PromptResponse) String() string { return proto.CompactTextString(m) }
func (*PromptResponse) ProtoMessage()    {}
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b032e72dba0447, []int{3}
}

func (m *PromptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptResponse.Unmarshal(m, b)
}
func (m *PromptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptResponse.Marshal(b, m, deterministic)
}
func (m *PromptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptResponse.Merge(m, src)
}
func (m *PromptResponse) XXX_Size() int {
	return xxx_messageInfo_PromptResponse.Size(m)
}
func (m *PromptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PromptResponse proto.InternalMessageInfo

func (m *PromptResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*HostRequest)(nil), "prompt.HostRequest")
	proto.RegisterType((*HostResponse)(nil), "prompt.HostResponse")
	proto.RegisterType((*PromptRequest)(nil), "prompt.PromptRequest")
	proto.RegisterType((*PromptResponse)(nil), "prompt.PromptResponse")
}

func init() { proto.RegisterFile("service/prompt/prompt.proto", fileDescriptor_39b032e72dba0447) }

var fileDescriptor_39b032e72dba0447 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbf, 0x4f, 0xbc, 0x40,
	0x10, 0xc5, 0xbf, 0xfb, 0xd5, 0x20, 0x8c, 0xa7, 0xc5, 0xaa, 0x17, 0x82, 0x89, 0xb9, 0x50, 0x51,
	0x28, 0x5c, 0xce, 0xc2, 0xd8, 0x6a, 0x63, 0x63, 0x62, 0x28, 0xed, 0xb8, 0xbb, 0x11, 0x37, 0x1e,
	0xec, 0xba, 0xbb, 0x68, 0xe9, 0xbf, 0x6e, 0x6e, 0x7f, 0x10, 0xd6, 0x0a, 0xde, 0x63, 0xe6, 0x31,
	0x9f, 0x19, 0xb8, 0x54, 0x28, 0xbf, 0xd8, 0x06, 0x2b, 0x21, 0x79, 0x27, 0xb4, 0x7b, 0x94, 0x42,
	0x72, 0xcd, 0x69, 0x64, 0x55, 0xfe, 0x0c, 0xc7, 0x4f, 0x5c, 0xe9, 0x1a, 0x3f, 0x07, 0x54, 0x9a,
	0xe6, 0x30, 0x6b, 0x76, 0x3b, 0xfe, 0xfd, 0x62, 0xbe, 0xaa, 0x94, 0x2c, 0x48, 0x11, 0xd7, 0x81,
	0x47, 0x33, 0x88, 0x25, 0x2a, 0xc1, 0x7b, 0x85, 0xe9, 0xff, 0x05, 0x29, 0x92, 0x7a, 0xd4, 0xf9,
	0x16, 0x66, 0x36, 0xce, 0x6a, 0x7a, 0x05, 0xc0, 0xb6, 0xd8, 0x6b, 0xf6, 0xc6, 0x50, 0x9a, 0xb4,
	0xa4, 0x9e, 0x38, 0xfb, 0x2c, 0xa6, 0x6c, 0xb0, 0xc9, 0x8a, 0xeb, 0x51, 0xd3, 0x14, 0x8e, 0x3a,
	0x54, 0xaa, 0x69, 0x31, 0x3d, 0x30, 0x8d, 0x5e, 0xe6, 0x8f, 0x70, 0x62, 0x6b, 0xfc, 0xd8, 0x19,
	0xc4, 0x96, 0x67, 0xfc, 0xc9, 0xa8, 0xe9, 0x1c, 0x1c, 0xab, 0x1b, 0xd6, 0x93, 0x5f, 0xc3, 0xa9,
	0x0f, 0x71, 0xc3, 0x4e, 0xc1, 0x48, 0x08, 0xb6, 0xfa, 0x81, 0xc4, 0x56, 0xb3, 0xbe, 0xa5, 0x77,
	0x70, 0xb8, 0xa7, 0xa4, 0x67, 0xa5, 0xdb, 0xe9, 0x64, 0x85, 0xd9, 0x79, 0x68, 0xba, 0xc5, 0xfc,
	0x2b, 0xc8, 0x92, 0xd0, 0x7b, 0x88, 0x1c, 0xdc, 0x85, 0xaf, 0x0a, 0x40, 0xb2, 0xf9, 0x5f, 0xdb,
	0xb7, 0x3f, 0xac, 0x5e, 0x97, 0x2d, 0xd3, 0xef, 0xc3, 0xba, 0xdc, 0xf0, 0xae, 0xea, 0x06, 0xdd,
	0xb4, 0xd8, 0xdf, 0x30, 0xee, 0x5f, 0x2b, 0xf1, 0xd1, 0x56, 0xe1, 0xc5, 0xd7, 0x91, 0xb9, 0xf5,
	0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x81, 0x5d, 0x60, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PromptingClient is the client API for Prompting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromptingClient interface {
	// Host allows clients to perform prompt hosting.
	Host(ctx context.Context, opts ...grpc.CallOption) (Prompting_HostClient, error)
	// Prompt performs prompting using a specific prompter.
	Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error)
}

type promptingClient struct {
	cc *grpc.ClientConn
}

func NewPromptingClient(cc *grpc.ClientConn) PromptingClient {
	return &promptingClient{cc}
}

func (c *promptingClient) Host(ctx context.Context, opts ...grpc.CallOption) (Prompting_HostClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Prompting_serviceDesc.Streams[0], "/prompt.Prompting/Host", opts...)
	if err != nil {
		return nil, err
	}
	x := &promptingHostClient{stream}
	return x, nil
}

type Prompting_HostClient interface {
	Send(*HostRequest) error
	Recv() (*HostResponse, error)
	grpc.ClientStream
}

type promptingHostClient struct {
	grpc.ClientStream
}

func (x *promptingHostClient) Send(m *HostRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *promptingHostClient) Recv() (*HostResponse, error) {
	m := new(HostResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *promptingClient) Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error) {
	out := new(PromptResponse)
	err := c.cc.Invoke(ctx, "/prompt.Prompting/Prompt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptingServer is the server API for Prompting service.
type PromptingServer interface {
	// Host allows clients to perform prompt hosting.
	Host(Prompting_HostServer) error
	// Prompt performs prompting using a specific prompter.
	Prompt(context.Context, *PromptRequest) (*PromptResponse, error)
}

// UnimplementedPromptingServer can be embedded to have forward compatible implementations.
type UnimplementedPromptingServer struct {
}

func (*UnimplementedPromptingServer) Host(srv Prompting_HostServer) error {
	return status.Errorf(codes.Unimplemented, "method Host not implemented")
}
func (*UnimplementedPromptingServer) Prompt(ctx context.Context, req *PromptRequest) (*PromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prompt not implemented")
}

func RegisterPromptingServer(s *grpc.Server, srv PromptingServer) {
	s.RegisterService(&_Prompting_serviceDesc, srv)
}

func _Prompting_Host_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PromptingServer).Host(&promptingHostServer{stream})
}

type Prompting_HostServer interface {
	Send(*HostResponse) error
	Recv() (*HostRequest, error)
	grpc.ServerStream
}

type promptingHostServer struct {
	grpc.ServerStream
}

func (x *promptingHostServer) Send(m *HostResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *promptingHostServer) Recv() (*HostRequest, error) {
	m := new(HostRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Prompting_Prompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptingServer).Prompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prompt.Prompting/Prompt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptingServer).Prompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prompting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prompt.Prompting",
	HandlerType: (*PromptingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prompt",
			Handler:    _Prompting_Prompt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Host",
			Handler:       _Prompting_Host_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service/prompt/prompt.proto",
}
